-- Synthetic production-like starting point derived only from sanitized metadata.
create extension if not exists pgcrypto;

do $$ begin
  if not exists (select 1 from pg_roles where rolname='authenticated') then create role authenticated nologin; end if;
  if not exists (select 1 from pg_roles where rolname='service_role') then create role service_role nologin bypassrls; end if;
end $$;

create schema if not exists auth;
create or replace function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid;
$$;

create table public.deals (
  id uuid primary key default gen_random_uuid(), property_address text,
  beds integer, baths integer, condition text, seller_price numeric,
  arv numeric, repairs numeric, mao numeric, profit numeric, analysis text,
  created_at timestamptz, deal_rating text, wholesale_profit numeric,
  wholesale_rating text, flip_profit numeric, flip_rating text,
  estimated_rent numeric, monthly_cashflow numeric, rental_rating text,
  strategy_summary text, scanner_score numeric, source text,
  absentee_owner boolean, vacant boolean, tax_delinquent boolean,
  preforeclosure boolean, inherited_property boolean, code_violations boolean,
  years_owned numeric, motivation_score numeric, distress_tags text,
  rent numeric, price numeric, stage text, next_action text, due_date date,
  notes text, seller_ask numeric, latest_offer numeric, counter_offer numeric,
  objection text, negotiation_status text, assignment_fee numeric,
  closing_date date, owner_name text, acquisitions_rep text,
  dispositions_rep text, phone text,
  constraint deals_address_unique unique(property_address)
);

create table public.message_logs (
  id uuid primary key default gen_random_uuid(), deal_id uuid, phone text,
  message text, channel text, status text, created_at timestamptz,
  direction text,
  constraint message_logs_direction_check check(direction in ('inbound','outbound'))
);
create table public.buyers (id uuid primary key default gen_random_uuid(),name text,email text,phone text,target_areas text,max_price numeric,notes text,created_at timestamptz);
create table public.documents (id uuid primary key default gen_random_uuid(),deal_id uuid,doc_type text,title text,url text,notes text,created_at timestamptz,constraint documents_deal_id_fkey foreign key(deal_id) references public.deals(id));
create table public.comps (id uuid primary key default gen_random_uuid(),deal_id uuid,address text,sale_price numeric,sqft numeric,beds numeric,baths numeric,created_at timestamptz,constraint comps_deal_id_fkey foreign key(deal_id) references public.deals(id));
create table public.sequences (id uuid primary key default gen_random_uuid(),deal_id uuid,step_day integer,action_type text,status text,due_date date,created_at timestamptz,constraint sequences_deal_id_fkey foreign key(deal_id) references public.deals(id));

create table public."Deals" (id bigint generated by default as identity primary key,created_at timestamptz,phone text);
create table public.activities (id bigint generated by default as identity primary key,deal_id uuid references public.deals(id),type text,note text,created_at timestamptz);
create table public.leads (
  id uuid primary key default gen_random_uuid(),lead_type text,full_name text,email text,
  phone text,property_address text,city text,state text,zip_code text,
  property_condition text,timeline text,motivation text,asking_price numeric,
  notes text,lead_score integer,temperature_label text,created_at timestamptz
);
create index leads_created_at_idx on public.leads(created_at);
create index leads_lead_score_idx on public.leads(lead_score);
create index leads_temperature_idx on public.leads(temperature_label);

alter table public.deals enable row level security;
alter table public.message_logs enable row level security;
alter table public.buyers enable row level security;
alter table public.documents enable row level security;
alter table public.comps enable row level security;
alter table public.sequences enable row level security;
alter table public."Deals" enable row level security;
alter table public.activities enable row level security;
alter table public.leads enable row level security;
create policy "Allow all for now" on public.deals for all to public using(true);
create policy "Allow read access" on public.message_logs for select to public using(true);

insert into public.deals(id,property_address,beds,baths,condition,created_at,phone)
select ('10000000-0000-0000-0000-' || lpad(n::text,12,'0'))::uuid,
       'Synthetic address ' || n, 3, 2, 'legacy', now(), '555000' || lpad(n::text,4,'0')
from generate_series(1,16) n;

insert into public.message_logs(id,deal_id,phone,message,status,created_at,direction)
select ('20000000-0000-0000-0000-' || lpad(n::text,12,'0'))::uuid,
       ('10000000-0000-0000-0000-' || lpad(n::text,12,'0'))::uuid,
       '555000' || lpad(n::text,4,'0'), 'Synthetic message ' || n,
       'received', now(), 'inbound'
from generate_series(1,7) n;

insert into public."Deals"(created_at,phone) values(now(),'5559990000');
insert into public.activities(deal_id,type,note,created_at) values('10000000-0000-0000-0000-000000000001','synthetic','synthetic note',now());
insert into public.leads(lead_type,lead_score,temperature_label,created_at) values('synthetic',1,'synthetic',now());
